version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d e-commerce"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: spring_boot_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: e-commerce
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/e-commerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SERVER_ERROR_INCLUDE_MESSAGE: always
      SSL_ENABLED: "true"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
